FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
COPY packages/ ./packages/
COPY apps/api/ ./apps/api/
COPY prisma/ ./prisma/

RUN npm install
RUN npm --prefix packages/shared-types run build
RUN npm --prefix packages/validation run build
RUN npm --prefix packages/config run build
RUN npx prisma generate
RUN npm --prefix apps/api run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app /app

EXPOSE 4000
CMD ["npm", "--prefix", "apps/api", "run", "start"]
